spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/basetemplate_dev
    username: default_dev_user
    password: ""

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  web:
    resources:
      chain:
        enabled: true

  mail:
    host:
    port: 587
    username:
    password:
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          from:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: BaseScheduler
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          threadPool:
            threadCount: 10
            threadPriority: 5

server:
  port: 8081
  servlet:
    context-path: /base-template

logging:
  level:
    root: INFO
  file:
    name: /var/base-template/application.log

jwt:
  secret: "placeholder-weak-default-jwt-secret-needs-override-abcdefghijklmnopqrstuvwxyz1234567890"
  expiration:
    days: 1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

app:
  swagger:
    baseurl: http://localhost:8081/base-template
    baseurl-https: https://localhost:8081/base-template
  static:
    path: file:/opt/base-template/resource/
  initialize:
    file:
      path: file:/opt/base-template/resource/initialize/
  audit:
    level: ALL
    day: 10

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,beans,env,mappings,loggers"